---

- hosts: all
  tasks:
  - name: test connection
    ping:

  roles:
  - ansible-base
  - ansible-sshd

- hosts: ipsec_gateways
  roles:
    - ansible-strongswan

  tasks:
    - name: Enable Firewall
      include: ./tasks/ufw.yml
