---

- hosts: prometheus
  roles:
  - ansible-prometheus
  - ansible-grafana

  vars:
    prometheus_web_external_url: "http://prometheus.open-infrastructure.de"
    prometheus_targets:
      node:
      - targets:
        - localhost:9100
        - fsn1-gw1.vpn.open-infrastructure.de:9100
        - de-bra-1.jitsi.rocks:9100
        - de-wob-1.jitsi.rocks:9100
        - de-fsn-1.jitsi.rocks:9100
        - de-fsn-2.jitsi.rocks:9100
        - de-nue-1.jitsi.rocks:9100
        - de-nue-2.jitsi.rocks:9100
        - fi-hel-2.jitsi.rocks:9100
        - fi-hel-2.jitsi.rocks:9100
        - nl-ams-1.jitsi.rocks:9100
        - us-nyc-1.jitsi.rocks:9100
        - gb-lon-1.jitsi.rocks:9100
        - bbb.jitsi.rocks:9100
        - bbb1.jitsi.rocks:9100
    grafana_address: "prometheus.open-infrastructure.de"
    grafana_port: 3000
    grafana_auth:
      anonymous:
        org_name: "Open Data"
        org_role: Viewer
      basic:
        enabled: true
    grafana_security:
      admin_user: admin
      admin_password: grafanaSecureAdminPassword1234
