---

- name: Install prometheus
  import_role:
    name: ansible-prometheus
    vars_from: prometheus.yml

- name: Enable prometheus Port
  ufw:
    rule: allow
    port: '9090'

- name: Enable node_exporter Port
  ufw:
    rule: allow
    port: '9100'

